### ISSUE TITLE
Add automatic --wizard command that generates menus and prompts

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#24]
The structure of `Command` permits an interactive mode that generates menus and prompts, e.g.:

```
Please enter the command you would like to execute:

1. commit — Commits the changes
2. version — Prints out the version
...


Please enter the boolean flags you would like to use:

[ ] (f) Force — Forces the deletion
[ ] (r) Remove — Removes the files

Please enter any combination of r, f: 
```

This ticket is to prototype such a wizard mode, which will walk the user through providing arguments and options using interactive menu prompts.

**Comment by ioreskovic** [comment]
Heya, I'd like to give this a go!

**Comment by jdegoes** [comment]
@ioreskovic This one will be great fun!

There are a few steps:

1. Adding a new Options for a `--wizard` mode.
2. Ensuring CLIApp will run the wizard when `--wizard` is specified.
3. The Wizard implementation will be different for each type of Command. But for those commands that have options / arguments, they will match on the Options / Args, and prompt the user for them.
4. Eventually when all information has been collected, then the wizard can generate the command-line arguments as `List[String]`.
5. Finally, the wizard can invoke `CLIApp#run` on the generated command-line arguments. Also, it would be helpful to print out these command-line arguments to the user, so they don't have to use the wizard again if they don't  want. Something like:
    ```
    You may bypass the wizard and execute your command directly with the following options and arguments:
      --verbose 3 foo.txt --port 2334
    ```

You might find a person or two to pair with on the Discord (if you like). In any case, please reach out if you run into any issues or have any questions!

**Comment by ioreskovic** [comment]
Thx for the hints @jdegoes!

I have a question right away, something that came to my mind during Adam's talk.

Should wizard usage be permitted with semi-completed command-line args?

For example, let's say there are 2 commands, `foo` and `bar`, and `foo` has 3 options and 2 arguments, `optA`, `optB`, `optC` & `arg1`, `arg2`. Would the following usage be valid/doable?

```shell script
cli-app foo --optA 10 --optC "myArg1" --wizard
```

My assumption is that the wizard would do the following:
1. Ask to confirm `optA` showing currently selected value
Something like:

The issue here might be the clash in clearing the flag or confirming. My current experience was that ___Enter___ with empty input confirms it, but then the question is how to clear it. Some special string/character? The name of the 

2. Ask for `optB`
Here the empty input would be just ignoring it, so no problems like in 1st step.

3. Ask to confirm `optC`
Again, same issue as 1st step

4. Confirm `arg1`
Again, same issue :(

5. Ask for `arg2`
Happy case :D

So, concrete question:
Is such a scenario viable?

If so, taking myself as a user, if I already specified an option/argument, it would just annoy me to have to confirm it again. Therefore, I would not ask for further wizard input on already specified flags/args.
However, there are people who just might want that, to double-check everything.

WDYT?

**Comment by ioreskovic** [comment]
@jdegoes 
I don't think I'll be able to get this done in time for Hackaton, I found it to be much trickier than I initially assessed. :disappointed:
Nevertheless, I'd like to continue working on it in my spare time. Is that OK?

**Comment by jdegoes** [comment]
@ioreskovic Yes, it's fine to work on after the hackathon. Let me know if you need any help and be sure to fill out the form to claim your t-shirt!

**Comment by ioreskovic** [comment]
@jdegoes I was finally able to pick this up, and I have some questions/issues about how `CliApp#run` is structured, mainly when it comes to subcommands.

Let's take a subset of `git`

```
git
git stash
git stash push
git stash clear
git push
```

Then, using recursive encoding, it looks like this:

```
Subcommand(            <- 
  Single(git),         <- Opts(version: Boolean), Args()
  Fallback(            <- 
    Subcommand(        <- 
      Single(stash),   <- Opts(), Args()
      Fallback(        <- 
        Single(push),  <- Opts(force: Boolean), Args(files: List[Path])
        Single(clear)  <- Opts(), Args()
      )                <- 
    ),                 <- 
    Single(push)       <- Opts(repo: Option[String]), Args(files: List[Path])
  )                    <- 
)                      <- 
```

Now, let's take a look at type `A` in `Command[+A]` for the following structure.

```scala
  final case class GitModel(version: Boolean)
  case object GitStashModel
  final case class GitStashPushModel(force: Boolean)
  case object GitStashClearModel
  final case class GitPushModel(repo: Option[String])

  val git: Command[((GitModel, Unit), (Product, Serializable))] =
    Command("git", Options.bool("version", true).as(GitModel), Args.Empty).subcommands(
      Command("stash", Options.Empty.map(_ => GitStashModel), Args.Empty)
        .subcommands(
          Command("push", Options.bool("force", ifPresent = true).as(GitStashPushModel), Args.file("files", Exists.Yes).repeat1),
          Command("clear", Options.Empty.map(_ => GitStashClearModel), Args.Empty)
        ),
      Command("push", Options.text("repo").optional("Use different repository").as(GitPushModel), Args.file("files", Exists.Yes).repeat1)
    )
```

As we can see here, inferred type is `Command[((GitModel, Unit), (Product, Serializable))]`, which is not that helpful, especially when you need to "extract" a certain subcommand to execute. Extracting the command from the tree to run it, to my understanding, is required because of the structure of `run` effect:

```scala
  def run(args: List[String]): ZIO[R with Console, Nothing, ExitCode] =
    (for {
      builtInValidationResult  <- command.parseBuiltIn(args, config)
      (remainingArgs, builtIn) = builtInValidationResult
      _                        <- handleBuiltIn(args, builtIn)
      validationResult         <- command.parse(remainingArgs, config)
    } yield validationResult)
      .foldM(printDocs, success => execute(success._2))
      .exitCode
```

Since wizard is a built-in, it should be handled by `handleBuiltIn` and instead of `Unit` in `ZIO[Console, Nothing, Unit]` return something more descriptive.

My initial idea was to either return `List[String]`, where it would represent wizard-generated args & opts, and for other cases in `handleBuiltIn`, empty list. However, then `command#parse` would have to take those generated opts, args (and **subcommands**, since you want to run `git stash push --force build.sbt`, for example), traverse the recursive structure, and return a **top-level** model in order to be able to `execute` it.

But, since that model differs (nested commands may have different models than the top one) from the one `execute` operates, I cannot execute it.

Another possible approach would be to have `wizard` also execute the command, and then short-circuit the rest of the code in `run`, effectively making it not that much transparent, when you look at the code, and possibly "abusing" the types to signal that wizard has already executed it "internally", and that the rest of the code should simply not do anything. I have fiddled a bit with it, so I still do not have concrete examples of what might go wrong/ugly.

I don't have much experience with recursion schemes, but this smells a bit like it to me, since we have a recursive data structure, which we want to be able to traverse independently of performing specific operations on it's data.

However, as I mentioned earlier, the types are giving me a problem, since they do not need to be a part of ADT (or an `HList`).
Ideally, I would like to achieve the following user-experience akin to this:

```scala
sealed trait GitCommand
final case class Git(...) extends GitCommand
case object GitStash extends GitCommand
final case class GitStashPush(...) extends GitCommand
...

val command: Command[ArgsAndOptsADT] = ...

val result = command.execute {
  case Git(version: Boolean) => ...
  case GitStash => ...
  case GitStashPush(force: Boolean, files: List[Path]) => ...
  ...
}
```

but I am not sure how to do it.

Any thoughts?

**Comment by jdegoes** [comment]
I think you should not care about the types at all, and simply generate a `List[String]` which will be parsed and processed via the ordinary mechanisms for doing so. 

Note that in a real application, when you use `.subcommands`, you would feed it commands that generate a sum type (`sealed trait`), rather than different, unrelated case classes.

**Comment by jdegoes** [comment]
We could do a pair programming session for 30 minutes, would that help?

**Comment by ioreskovic** [comment]
I would love to, but my timetable is packed until Wednesday.
I'll try to fiddle with it until Wednesday, and then reach you on Discord if I still have issues? Is that OK?

**Comment by jdegoes** [comment]
Yes, sounds good!

**Comment by jdegoes** [comment]
@jorge-vasquez-2301 If you are interested in finishing this ticket (with the menus, prompts and other deluxe features), feel free to /attempt #24
