### ISSUE TITLE
Implement Magnolia derivation for user-defined ADTs

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#37]
A user-defined ADT, consisting of sealed traits, case classes, and strings/collections, could, in theory, be used to derive a `Command` that produces a data structure of that type.

For example:

```scala
case class WordCount(c: Boolean, l: Boolean, w: Boolean)

val wordCount: Command[WordCount] = DeriveCommand.genCommand
```

This can be done using Magnolia, and following a pattern similar to ZIO JSON.

We should also add annotations to provide custom details which cannot be inferred from the structure of the ADT alone.

**Comment by vladimir-popov** [comment]
I will take it with @asakaev and @sapizhak

**Comment by jdegoes** [comment]
@vladimir-popov Awesome. Good luck and let me know if you need any hints / further clarifications!

**Comment by vladimir-popov** [comment]
@jdegoes how we can derive an arbitrary class for command when it could be derived from options or form args or from both?
```scala
val wc: Command[(WcOptions, ::[Path])] = Command("wc", options, args)
```

**Comment by vladimir-popov** [comment]
I think we can derive both `Options` and `Args`, and separate `Command`'s type parameter on two explicitly different: 
```scala
Command[+Op, +Arg]
```

**Comment by sapizhak** [comment]
We are not really sure that the automatic derivation of Commands requires implementation. Current type signature of `Command` does not provide information about types that define `Options` and `Args`. Furthermore we are unable to tell from the case class signature what defines it application - a set of `Options`, set of `Args` or both of them. 

We might have solved this by widening the `Command[+A]` to `Command[+A, +B]` to derive `Options` and `Args` separately in compile time to push them to a further derivation in sum types. Nevertheless we doubt this decision as well, because compiler would be unable to choose an instance for a type like `Options[Boolean]` in a case class like `Command(x: Boolean, y: Boolean)` as many `Options[Boolean]` implemented instances with various behaviours applied to each of them will be available in scope.

To avoid this, an annotation like `@ifPresent` can be added to override a default behaviour of an existing `Options[A]` instance ```case class WordCount(@ifPresent(true) c: Boolean)```

Such decision makes too much "noise" for the whole project and is a huge overhead because of a massive extension of `Command` type system (probably a use of `shapeless` or complex usage of `magnolia` is not encouraged in such a lightweight project with a very narrow use case). A simple `Command.Single` apply method is a much better and precise decision.

**Comment by jdegoes** [comment]
I am closing this for now, but I saw how Li took this approach for his new library:

[mainargs](https://github.com/lihaoyi/mainargs)
