### ISSUE TITLE
Support boolean option grouping

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-cli#71]
Grouping is a feature whereby boolean, single-letter flags may be clustered together.

For example, instead of writing:

```
wc -l -c -w
```

You could write:

```
wc -lcw
```

Supporting this is tricky, because it requires two things:

1. All of the clustered options need to be of type boolean.
2. The clustered option cannot match any other option.

This seems to require "global knowledge" but right now the validation / parsing only has "local" knowledge; that is, every Options may only have access to part of the command-line arguments and may not know about the decisions about other Options and Args.

**Comment by vdeclerk** [comment]
I'm looking at this issue.

Since Options assume:

`
private def makeFullName(s: String): String = (if (s.length == 1) "-" else "--") + s
`

Can't we "unCluster" the args that have length > 1 and start with "-"  when parsing?
If matching options of length different to 1 exist should start with "--".
I'm talking about transforming for example:
wc -cw filename
To
wc -c -w filename
Before validating the options.
Not sure of which problems could arise If one of the options are not boolean in this case.
